version: '3.8'
services:
  job_api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app

  frontend:
    build:
      context: ./frontend
    container_name: job_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - job_api

