# Node 20 kullan
FROM node:20-slim

# Çalışma dizini
WORKDIR /app

# package.json ve package-lock.json kopyala ve bağımlılıkları yükle
COPY package*.json ./
RUN npm install

# Tüm frontend dosyalarını kopyala
COPY . .

# Port
EXPOSE 5173

# Geliştirme server'ını çalıştır
CMD ["npm", "run", "dev", "--", "--host"]

