# Python 3.12 kullan
FROM python:3.12-slim

# Çalışma dizini
WORKDIR /app

# Gereksinimleri kopyala ve yükle
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Tüm backend dosyalarını kopyala
COPY . .

# Port
EXPOSE 5000

# Uygulamayı çalıştır
CMD ["python", "run.py"]
